export const FETCH_LATEST_MOVIES= 'FETCH_LATEST_MOVIES';
export const FETCH_UPCOMING_MOVIES= 'FETCH_UPCOMING_MOVIES';
export const FETCH_POPULAR_MOVIES= 'FETCH_POPULAR_MOVIES';
export const FETCH_TOP_RATED_MOVIES= 'FETCH_TOP_RATED_MOVIES';